---
- name: stop firewall 
  shell: |
     yes 'y' | ufw disable
     
- name: default ufw pol
  shell: |
    ufw default deny incoming
    ufw default allow outgoing

- name: allowing http/https/ssh
  shell: |
    ufw allow http
    ufw allow https
    ufw allow ssh
    yes 'y' | ufw enable


