- name: Copy files to server
  copy:
    src: files/plausible/
    dest: "/home/{{  user  }}/plausible"
    force: true

- name: templating plausible config file to server
  template:
    src: templates/plausible-conf.j2
    dest: /home/{{  user  }}/plausible/plausible-conf.env
    force: true

- name: templating smtp config file to server
  template:
    src: templates/plausible-smtp.j2
    dest: /home/{{  user  }}/plausible/plausible-smtp.env
    force: true 

- name: docker compose plausible
  shell: |
    cd plausible && docker stack deploy -c docker-compose.yml plausible

